{% set name = "loadmydata" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/loadmydata-{{ version }}.tar.gz
  sha256: 7e528827ff59831bcbd895c061ef7e65c02e0dd16822119b316210f6e0bb02ff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm >=3.4
  run:
    - numpy
    - pandas
    - python >=3.6
    - requests
    - scikit-learn >=0.23.0
    - scipy >=1.3.0
    - tqdm
    - yarl

test:
  imports:
    - loadmydata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepcharles/loadmydata
  summary: Collections of utility functions to download open-source data sets.
  dev_url: https://github.com/deepcharles/loadmydata/
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - deepcharles
